projects:
  smoothstarApiServer:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: bqz6rov3xrggfe6wibumtjff6u
      endpoints:
        prod: >-
          https://bn3sc7dzlbchpclda3idufzoka.appsync-api.eu-west-1.amazonaws.com/graphql
