export const ActionTypes = {
  CLEAR_ERR_MSG: 'CLEAR_ERR_MSG',
  //AUTH ACTIONS
  AUTH_INITIATE: 'AUTH_INITIATE',
  AUTH_COMPLETED: 'AUTH_COMPLETED',
  CLEAR_AUTH: 'CLEAR_AUTH',
  SET_AUTH_ACTION_COMPLETED: 'SET_AUTH_ACTION_COMPLETED',
  CONFIRM_SIGNUP: 'CONFIRM_SIGNUP',
  CONFIRM_SIGNIN: 'CONFIRM_SIGNIN',
  SET_INIT_LAUNCH: 'SET_INIT_LAUNCH',
  UPDATE_ATTRIBUTES: 'UPDATE_ATTRIBUTES',
  //APP ACTIONS
  READY_APP: 'READY_APP',
  API_INITIATE: 'API_INITIATE',
  API_COMPLETED: 'API_COMPLETED',
  UNSUB_STATE: 'UNSUB_STATE',
  FETCH_LIST_NEWS: 'FETCH_LIST_NEWS',
  FETCH_LIST_EVENTS: 'FETCH_LIST_EVENTS',
  CREATE_SS_REGISTRATION: 'CREATE_SS_REGISTRATION',
  UPDATE_SS_REGISTRATION: 'UPDATE_SS_REGISTRATION',
  CHECK_SS_REGISTRATION: 'CHECK_SS_REGISTRATION',
};
