export const ActionTypes = {
  CLEAR_ERR_MSG: 'CLEAR_ERR_MSG',
  //AUTH ACTIONS
  AUTH_INITIATE: 'AUTH_INITIATE',
  AUTH_COMPLETED: 'AUTH_COMPLETED',
  SET_AUTH: 'SET_AUTH',
  CLEAR_AUTH: 'CLEAR_AUTH',
  SET_AUTH_ACTION_COMPLETED: 'SET_AUTH_ACTION_COMPLETED',
  CONFIRM_SIGNUP: 'CONFIRM_SIGNUP',
  CONFIRM_SIGNIN: 'CONFIRM_SIGNIN',
  //APP ACTIONS
  API_INITIATE: 'API_INITIATE',
  API_COMPLETED: 'API_COMPLETED',
  FETCH_LIST_NEWS: 'FETCH_LIST_NEWS',
  CREATE_SS_REGISTERATION: 'CREATE_SS_REGISTERATION',
  SEARCH_ORDER_INFO: 'SEARCH_ORDER_INFO',
  SEARCH_OCR_INFO: 'SEARCH_OCR_INFO',
  UNSUB_STATE: 'UNSUB_STATE',
};
