export const Colors = {
  backgroundColor: '#fff',
  headerTitleColor: '#fff',
  primaryTextColor: '#000',
  secondaryTextColor: '#fff',
  greyTextColor: '#aaa',
  textShadowColor: '#4d4c4c',
  inputBoxColor: '#aaa',
  inputBoxTextColor: '#000',
  buttonNormalColor: '#000',
  buttonGoogleColor: '#f52d56',
  buttonFBColor: '#3b5998',
  buttonTextColor: '#fff',
  checkBoxColor: '#aaa',
  imageBackgroundColor: '#ddd',
};
