export const Colors = {
  backgroundColor: '#fff',
  headerTitleColor: '#fff',
  primaryTextColor: '#5d5d5d',
  secondaryTextColor: '#fff',
  tertiaryTextColor: '#000',
  greyTextColor: '#aaa',
  textShadowColor: '#4d4c4c',
  inputBoxColor: '#aaa',
  inputBoxTextColor: '#000',
  inputBoxIconColor: '#000',
  inputBoxDisabledColor: '#ddd',
  buttonNormalColor: '#000',
  buttonDisableColor: '#ddd',
  buttonDisableTextColor: '#aaa',
  buttonGoogleColor: '#f52d56',
  buttonFBColor: '#3b5998',
  buttonTextColor: '#fff',
  checkBoxColor: '#aaa',
  imageBackgroundColor: '#ddd',
  bulletColor: '#00bff3',
  bulletTextColor: '#fff',
  switchOnColor: '#00bff3',
  switchOffColor: '#666666',
  switchGripColor: '#fff',
  tooltipColor: '#000',
  tooltipTextColor: '#fff',
};
